#include "magphos_compiler.h"

#include <algorithm>
#include <regex>
#include <sstream>
#include <stdexcept>
#include <string>

#include "multiraptor.h"

namespace {

std::string trim(const std::string& input) {
    const auto first = input.find_first_not_of(" \t\r\n");
    if (first == std::string::npos) {
        return "";
    }
    const auto last = input.find_last_not_of(" \t\r\n");
    return input.substr(first, last - first + 1);
}

std::string indentation(int depth) {
    return std::string(static_cast<std::size_t>(std::max(0, depth)) * 2, ' ');
}

std::string escapeBackticks(const std::string& value) {
    std::string out;
    out.reserve(value.size());
    for (char c : value) {
        if (c == '`') {
            out += "\\`";
        } else {
            out += c;
        }
    }
    return out;
}

} // namespace

namespace magphos {

std::string compileToJavaScript(const std::string& source) {
    std::stringstream input(source);
    std::string line;
    std::string output;
    output += "// Generated by " + languageName() + " C++ compiler\n";
    output += "'use strict';\n";

    std::size_t lineNo = 0;
    int indent = 0;
    bool inBlockComment = false;

    while (std::getline(input, line)) {
        ++lineNo;
        std::string text = trim(line);

        if (inBlockComment) {
            if (text.find("!/") != std::string::npos) {
                inBlockComment = false;
            }
            continue;
        }

        if (text.rfind("//!", 0) == 0) {
            inBlockComment = true;
            continue;
        }

        if (text.empty() || text.rfind("//", 0) == 0 || text.rfind("#", 0) == 0 || text.rfind("/!", 0) == 0) {
            continue;
        }

        if (text == "}") {
            indent = std::max(0, indent - 1);
            output += indentation(indent) + "}\n";
            continue;
        }

        if (text == "else {") {
            indent = std::max(0, indent - 1);
            output += indentation(indent) + "else {\n";
            indent += 1;
            continue;
        }

        std::smatch match;
        if (std::regex_match(text, match, std::regex(R"(^var\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.+)$)"))) {
            output += indentation(indent) + "let " + match[1].str() + " = " + match[2].str() + ";\n";
        } else if (std::regex_match(text, match, std::regex(R"(^const\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.+)$)"))) {
            output += indentation(indent) + "const " + match[1].str() + " = " + match[2].str() + ";\n";
        } else if (std::regex_match(text, match, std::regex(R"(^set\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.+)$)"))) {
            output += indentation(indent) + match[1].str() + " = " + match[2].str() + ";\n";
        } else if (std::regex_match(text, match, std::regex(R"(^print\s+(.+)$)"))) {
            output += indentation(indent) + "console.log(" + match[1].str() + ");\n";
        } else if (std::regex_match(text, match, std::regex(R"(^ask\s+(.+)\s*->\s*([A-Za-z_][A-Za-z0-9_]*)$)"))) {
            output += indentation(indent) + "let " + match[2].str() + " = prompt(" + match[1].str() + ") ?? \"\";\n";
        } else if (std::regex_match(text, match, std::regex(R"(^if\s+(.+)\s*\{$)")) ||
                   std::regex_match(text, match, std::regex(R"(^when\s+(.+)\s*\{$)"))) {
            output += indentation(indent) + "if (" + match[1].str() + ") {\n";
            indent += 1;
        } else if (std::regex_match(text, match, std::regex(R"(^loop\s+(.+)\s*\{$)"))) {
            output += indentation(indent) + "for (let __mp_i = 0; __mp_i < (" + match[1].str() + "); __mp_i += 1) {\n";
            indent += 1;
        } else if (std::regex_match(text, match, std::regex(R"(^repeat\s+while\s+(.+)\s*\{$)"))) {
            output += indentation(indent) + "while (" + match[1].str() + ") {\n";
            indent += 1;
        } else if (std::regex_match(text, match, std::regex(R"(^fn\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(([^)]*)\)\s*\{$)"))) {
            output += indentation(indent) + "function " + match[1].str() + "(" + match[2].str() + ") {\n";
            indent += 1;
        } else if (std::regex_match(text, match, std::regex(R"(^return\s+(.+)$)"))) {
            output += indentation(indent) + "return " + match[1].str() + ";\n";
        } else if (text == "stop") {
            output += indentation(indent) + "break;\n";
        } else if (text == "next") {
            output += indentation(indent) + "continue;\n";
        } else {
            throw std::runtime_error("Syntax error at line " + std::to_string(lineNo) + ": `" + escapeBackticks(text) + "`");
        }
    }

    if (indent != 0) {
        throw std::runtime_error("Syntax error: mismatched braces.");
    }

    return output;
}

} // namespace magphos
