function trim(v) { return v.trim(); }

function compileMagPhos(source) {
  const lines = source.split(/\r?\n/);
  let indent = 0;
  let out = "// Generated by MagPhos browser compiler\n'use strict';\n";
  let inBlockComment = false;
  const pad = (n) => ' '.repeat(n * 2);

  for (let i = 0; i < lines.length; i += 1) {
    const text = trim(lines[i]);
    if (inBlockComment) { if (text.includes('!/')) inBlockComment = false; continue; }
    if (text.startsWith('//!')) { inBlockComment = true; continue; }
    if (!text || text.startsWith('//') || text.startsWith('#') || text.startsWith('/!')) continue;
    if (text === '}') { indent = Math.max(0, indent - 1); out += `${pad(indent)}}\n`; continue; }
    if (text === 'else {') { indent = Math.max(0, indent - 1); out += `${pad(indent)}else {\n`; indent += 1; continue; }
    let m;
    if ((m = text.match(/^var\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.+)$/))) out += `${pad(indent)}let ${m[1]} = ${m[2]};\n`;
    else if ((m = text.match(/^const\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.+)$/))) out += `${pad(indent)}const ${m[1]} = ${m[2]};\n`;
    else if ((m = text.match(/^set\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.+)$/))) out += `${pad(indent)}${m[1]} = ${m[2]};\n`;
    else if ((m = text.match(/^print\s+(.+)$/))) out += `${pad(indent)}console.log(${m[1]});\n`;
    else if ((m = text.match(/^ask\s+(.+)\s*->\s*([A-Za-z_][A-Za-z0-9_]*)$/))) out += `${pad(indent)}let ${m[2]} = prompt(${m[1]}) ?? "";\n`;
    else if ((m = text.match(/^if\s+(.+)\s*\{$/)) || (m = text.match(/^when\s+(.+)\s*\{$/))) { out += `${pad(indent)}if (${m[1]}) {\n`; indent += 1; }
    else if ((m = text.match(/^loop\s+(.+)\s*\{$/))) { out += `${pad(indent)}for (let __mr_i = 0; __mr_i < (${m[1]}); __mr_i += 1) {\n`; indent += 1; }
    else if ((m = text.match(/^repeat\s+while\s+(.+)\s*\{$/))) { out += `${pad(indent)}while (${m[1]}) {\n`; indent += 1; }
    else if ((m = text.match(/^fn\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(([^)]*)\)\s*\{$/))) { out += `${pad(indent)}function ${m[1]}(${m[2]}) {\n`; indent += 1; }
    else if ((m = text.match(/^return\s+(.+)$/))) out += `${pad(indent)}return ${m[1]};\n`;
    else if (text === 'stop') out += `${pad(indent)}break;\n`;
    else if (text === 'next') out += `${pad(indent)}continue;\n`;
    else throw new Error(`Syntax error at line ${i + 1}: ${text}`);
  }
  if (indent !== 0) throw new Error('Syntax error: mismatched braces');
  return out;
}

window.addEventListener('DOMContentLoaded', () => {
  const sourceEl = document.getElementById('source');
  const compiledEl = document.getElementById('compiled');
  const outputEl = document.getElementById('output');
  function doCompile() { const js = compileMagPhos(sourceEl.value); compiledEl.textContent = js; return js; }
  document.getElementById('compileBtn').addEventListener('click', () => { outputEl.textContent = ''; try { doCompile(); } catch (err) { outputEl.textContent = err.message; }});
  document.getElementById('runBtn').addEventListener('click', () => { outputEl.textContent = ''; try { const js = doCompile(); const logs = []; const originalLog = console.log; console.log = (...args) => logs.push(args.join(' ')); try { new Function(js)(); } finally { console.log = originalLog; } outputEl.textContent = logs.join('\n') || '(no output)'; } catch (err) { outputEl.textContent = err.message; }});
  document.getElementById('compileBtn').click();
});
