const STORAGE_KEY = 'magphos-web-studio-v1';

function trim(v) {
  return v.trim();
}

function compileMagPhos(source) {
  const lines = source.split(/\r?\n/);
  let indent = 0;
  let out = "// Generated by MagPhos browser compiler\n'use strict';\n";
  let inBlockComment = false;

  const pad = (n) => ' '.repeat(n * 2);

  for (let i = 0; i < lines.length; i += 1) {
    const text = trim(lines[i]);

    if (inBlockComment) {
      if (text.includes('!/')) inBlockComment = false;
      continue;
    }

    if (text.startsWith('//!')) {
      inBlockComment = true;
      continue;
    }

    if (!text || text.startsWith('//') || text.startsWith('#') || text.startsWith('/!')) continue;

    if (text === '}') {
      indent = Math.max(0, indent - 1);
      out += `${pad(indent)}}\n`;
      continue;
    }

    if (text === 'else {') {
      indent = Math.max(0, indent - 1);
      out += `${pad(indent)}else {\n`;
      indent += 1;
      continue;
    }

    let m;
    if ((m = text.match(/^var\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.+)$/))) {
      out += `${pad(indent)}let ${m[1]} = ${m[2]};\n`;
    } else if ((m = text.match(/^const\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.+)$/))) {
      out += `${pad(indent)}const ${m[1]} = ${m[2]};\n`;
    } else if ((m = text.match(/^set\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.+)$/))) {
      out += `${pad(indent)}${m[1]} = ${m[2]};\n`;
    } else if ((m = text.match(/^print\s+(.+)$/))) {
      out += `${pad(indent)}console.log(${m[1]});\n`;
    } else if ((m = text.match(/^ask\s+(.+)\s*->\s*([A-Za-z_][A-Za-z0-9_]*)$/))) {
      out += `${pad(indent)}let ${m[2]} = prompt(${m[1]}) ?? "";\n`;
    } else if ((m = text.match(/^if\s+(.+)\s*\{$/)) || (m = text.match(/^when\s+(.+)\s*\{$/))) {
      out += `${pad(indent)}if (${m[1]}) {\n`;
      indent += 1;
    } else if ((m = text.match(/^loop\s+(.+)\s*\{$/))) {
      out += `${pad(indent)}for (let __mp_i = 0; __mp_i < (${m[1]}); __mp_i += 1) {\n`;
      indent += 1;
    } else if ((m = text.match(/^repeat\s+while\s+(.+)\s*\{$/))) {
      out += `${pad(indent)}while (${m[1]}) {\n`;
      indent += 1;
    } else if ((m = text.match(/^fn\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(([^)]*)\)\s*\{$/))) {
      out += `${pad(indent)}function ${m[1]}(${m[2]}) {\n`;
      indent += 1;
    } else if ((m = text.match(/^return\s+(.+)$/))) {
      out += `${pad(indent)}return ${m[1]};\n`;
    } else if (text === 'stop') {
      out += `${pad(indent)}break;\n`;
    } else if (text === 'next') {
      out += `${pad(indent)}continue;\n`;
    } else {
      throw new Error(`Syntax error at line ${i + 1}: ${text}`);
    }
  }

  if (indent !== 0) throw new Error('Syntax error: mismatched braces');
  return out;
}

function createDefaultProject() {
  const template = document.getElementById('defaultProgram').content.textContent;
  return {
    projectName: 'chromebook-studio',
    activeFile: 'main.mp',
    files: {
      'main.mp': template,
      'notes.mp': '# Put extra snippets here'
    }
  };
}

function loadProject() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return createDefaultProject();
    const parsed = JSON.parse(raw);
    if (!parsed || !parsed.files || !Object.keys(parsed.files).length) {
      return createDefaultProject();
    }
    return parsed;
  } catch (_) {
    return createDefaultProject();
  }
}

function saveProject(project) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(project));
}

const sourceEl = document.getElementById('source');
const compiledEl = document.getElementById('compiled');
const outputEl = document.getElementById('output');
const fileListEl = document.getElementById('fileList');
const activeFileLabel = document.getElementById('activeFileLabel');

let project = loadProject();

function ensureActiveFile() {
  if (!project.files[project.activeFile]) {
    project.activeFile = Object.keys(project.files)[0];
  }
}

function renderFileList() {
  ensureActiveFile();
  fileListEl.innerHTML = '';
  Object.keys(project.files).sort().forEach((fileName) => {
    const li = document.createElement('li');
    const btn = document.createElement('button');
    btn.className = 'file-btn';
    if (fileName === project.activeFile) btn.classList.add('active');
    btn.textContent = fileName;
    btn.addEventListener('click', () => {
      project.activeFile = fileName;
      syncEditorFromFile();
      renderFileList();
      saveProject(project);
    });
    li.appendChild(btn);
    fileListEl.appendChild(li);
  });
  activeFileLabel.textContent = `Editor — ${project.activeFile}`;
}

function syncEditorFromFile() {
  sourceEl.value = project.files[project.activeFile] ?? '';
}

function syncFileFromEditor() {
  project.files[project.activeFile] = sourceEl.value;
  saveProject(project);
}

function doCompile() {
  syncFileFromEditor();
  const js = compileMagPhos(sourceEl.value);
  compiledEl.textContent = js;
  return js;
}

sourceEl.addEventListener('input', () => {
  syncFileFromEditor();
});

document.getElementById('compileBtn').addEventListener('click', () => {
  outputEl.textContent = '';
  try {
    doCompile();
  } catch (err) {
    outputEl.textContent = err.message;
  }
});

document.getElementById('runBtn').addEventListener('click', () => {
  outputEl.textContent = '';
  try {
    const js = doCompile();
    const logs = [];
    const originalLog = console.log;
    console.log = (...args) => logs.push(args.join(' '));
    try {
      new Function(js)();
    } finally {
      console.log = originalLog;
    }
    outputEl.textContent = logs.join('\n') || '(no output)';
  } catch (err) {
    outputEl.textContent = err.message;
  }
});

document.getElementById('newFileBtn').addEventListener('click', () => {
  const name = prompt('New file name (example: utils.mp)');
  if (!name) return;
  const safeName = name.trim();
  if (!safeName) return;
  if (project.files[safeName]) {
    alert('File already exists.');
    return;
  }
  project.files[safeName] = '# New file';
  project.activeFile = safeName;
  saveProject(project);
  syncEditorFromFile();
  renderFileList();
});

document.getElementById('renameFileBtn').addEventListener('click', () => {
  const oldName = project.activeFile;
  const nextName = prompt('Rename file', oldName);
  if (!nextName || nextName.trim() === oldName) return;
  const safeName = nextName.trim();
  if (!safeName) return;
  if (project.files[safeName]) {
    alert('A file with that name already exists.');
    return;
  }
  project.files[safeName] = project.files[oldName];
  delete project.files[oldName];
  project.activeFile = safeName;
  saveProject(project);
  renderFileList();
});

document.getElementById('deleteFileBtn').addEventListener('click', () => {
  const allFiles = Object.keys(project.files);
  if (allFiles.length <= 1) {
    alert('You need at least one file in the project.');
    return;
  }
  if (!confirm(`Delete ${project.activeFile}?`)) return;
  delete project.files[project.activeFile];
  project.activeFile = Object.keys(project.files).sort()[0];
  saveProject(project);
  syncEditorFromFile();
  renderFileList();
});

document.getElementById('newProjectBtn').addEventListener('click', () => {
  if (!confirm('Create a new project? This replaces the current local project.')) return;
  project = createDefaultProject();
  saveProject(project);
  syncEditorFromFile();
  renderFileList();
  compiledEl.textContent = '';
  outputEl.textContent = '';
});

document.getElementById('exportBtn').addEventListener('click', () => {
  syncFileFromEditor();
  const blob = new Blob([JSON.stringify(project, null, 2)], { type: 'application/json' });
  const a = document.createElement('a');
  const fileStem = (project.projectName || 'magphos-project').replace(/\s+/g, '-');
  a.href = URL.createObjectURL(blob);
  a.download = `${fileStem}.json`;
  document.body.appendChild(a);
  a.click();
  a.remove();
});

document.getElementById('importInput').addEventListener('change', async (event) => {
  const file = event.target.files?.[0];
  if (!file) return;
  try {
    const text = await file.text();
    const parsed = JSON.parse(text);
    if (!parsed.files || !Object.keys(parsed.files).length) {
      throw new Error('Invalid project file.');
    }
    project = parsed;
    ensureActiveFile();
    saveProject(project);
    syncEditorFromFile();
    renderFileList();
    outputEl.textContent = `Imported ${file.name}`;
  } catch (err) {
    outputEl.textContent = err.message;
  } finally {
    event.target.value = '';
  }
});

syncEditorFromFile();
renderFileList();
document.getElementById('compileBtn').click();
